### ISSUE TITLE
Implement method to fetch netinfo for valid regions

### ISSUE THREAD

**Issue by 7bitlyrus** [rNintendoSwitch/nsecpy#9]
Implement a method and returns a network status dataclass for a given (supported) region.

Endpoint: https://www.nintendo.co.jp/netinfo/xx_XX/status.json
Example: https://www.nintendo.co.jp/netinfo/en_US/status.json

Road map:
- [x] Dataclass
- [x] Method
- [x] Tests

**Comment by mralext20** [comment]
discussion is needed regarding the date fields - they are plain english, ment to be sub'd into a corisponding string, somthing along the lines of "This event happens between $BEGIN and $END, times are Pacific timezone. "

in the case of a differnet language, e.g. pt_BR, or fr_CA, the $BEGIN and $END strings are localized, and contain month / week words as their localized format. 

i propose we leave these as localized strings.

**Comment by MattBSG** [comment]
That would assume the project is also to be translated for each region as well. If we look at the proposed use case of nsecpy, it is standardizing output. The main use of this library is tailored towards an english speaking user-base so it may make sense to convert. I do know that python datetime does support locales for strptime but it would require more research

**Comment by 7bitlyrus** [comment]
+ 1 for converting time strings to DateTime objects if possible

**Comment by 7bitlyrus** [comment]
@MattBSG 
> I do know that python datetime does support locales for strptime but it would require more research

I do know that @mralext20 brought up this library on Discord last night: https://pypi.org/project/dateparser/

**Comment by 7bitlyrus** [comment]
It looks like `dateparser`, given the test strings Alex posted last night:

```py
import dateparser

test_strings = {
    'en_US': (
        'Thursday, February 18, 2021  4 :55 PM'.replace(' :', ':'),
        'America/Los_Angeles',
    ),
    'fr_CA': (
        'jeudi 18 février 2021 à 19h55',
        'America/Montreal',
    ),
    'pt_BR': (
        'quinta, 18 de fevereiro de 2021 16:55',
        'America/Los_Angeles',  # Guess, buts it sure isn't a brazilian time zone
    ),
}

for r, (str, tz) in test_strings.items():
    t = dateparser.parse(str, settings={'TIMEZONE': tz, 'RETURN_AS_TIMEZONE_AWARE': True})
    print(f'{r}: {t}')
    
#>> en_US: 2021-02-18 16:55:00-08:00
#>> fr_CA: 2021-02-18 19:55:00-05:00
#>> pt_BR: 2021-02-18 16:55:00-08:00
```

**Comment by 7bitlyrus** [comment]
Prehaps we should use https://github.com/pnuckowski/aioresponses for mocking `aiohttp.ClientSession()`
